### ISSUE TITLE
Postjob should also send the affil. id and session id if they are included in the job tags

### ISSUE THREAD

**Issue by matthewling** [mediapeers/postjob#24]
# Current Status

Postjob sends *args but does seems to not unpack affil. id and session id should they be in the tags on the job.

This results in the following error when the runner picks up the add users to groups workflow:

```
..I, [2018-04-05T04:04:15.898379 #6336]  INFO -- : Running Postjob#19: Workflow::Base::AddUsersToGroup.run(52258, "(Application)")
E, [2018-04-05T04:04:15.898495 #6336] ERROR -- : missing keywords: affiliation_id, session_id, from
        app/workflows/add_users_to_group.rb:14:in `run'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob/runner.rb:118:in `public_send'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob/runner.rb:118:in `block in invoke_workflow'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob/runner.rb:109:in `catch'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob/runner.rb:109:in `invoke_workflow'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob/runner.rb:99:in `block in process_job'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob/runner.rb:26:in `with_current_job'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob/runner.rb:98:in `process_job'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob.rb:143:in `process_job'
        /home/vagrant/.gem/ruby/2.3.1/gems/postjob-0.3.4/lib/postjob.rb:132:in `step'
E, [2018-04-05T04:04:15.898603 #6336] ERROR -- : Postjob#19: Workflow::Base::AddUsersToGroup(52258, "(Application)") (processing) failed ArgumentError "missing keywords: affiliation_id, session_id": 0.009 secs
[10.316 secs] Processed job w/id 19
```

## Task

Also send the session id and affil. id in the args to the run method of the workflow.

See:  https://github.com/mediapeers/mpx-jc-app/blob/purpose/add-users-to-group-mass-action/app/workflows/add_users_to_group.rb#L14-L22

**Comment by matthewling** [comment]
@radiospiel moved this over from redmine, it slipped my mind that we're using github issues ... I hope I reported this correctly as it may need some thought due to required arguments ...
